%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ConsumerAdmin
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL).
-define(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL, true).




-endif.


