%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_erlang
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/ic/include/erlang.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_ERLANG_HRL).
-define(OE_ERLANG_HRL, true).




-endif.


