%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_RecoveryCoordinator
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_RECOVERYCOORDINATOR_HRL).
-define(COSTRANSACTIONS_RECOVERYCOORDINATOR_HRL, true).




-endif.


