%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_FileIterator
%% Source: /home/vagrant/build-dir_14-10-22_14-39-46/otp-support/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_FILEITERATOR_HRL).
-define(COSFILETRANSFER_FILEITERATOR_HRL, true).




-endif.


