%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_ProxyPushConsumer
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_PROXYPUSHCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_PROXYPUSHCONSUMER_HRL, true).




-endif.


