%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_Filter
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_FILTER_HRL).
-define(COSNOTIFYFILTER_FILTER_HRL, true).




-endif.


