%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotificationComm_Event
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/cosNotification/src/cosNotificationAppComm.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFICATIONCOMM_EVENT_HRL).
-define(OE_COSNOTIFICATIONCOMM_EVENT_HRL, true).




-endif.


