%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotification
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/cosNotification/src/CosNotification.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFICATION_HRL).
-define(OE_COSNOTIFICATION_HRL, true).




-endif.


