%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_FileTransferSession
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_FILETRANSFERSESSION_HRL).
-define(COSFILETRANSFER_FILETRANSFERSESSION_HRL, true).




-endif.


