%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_PushSupplier
%% Source: /home/vagrant/build-dir_14-10-22_14-39-46/otp-support/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_PUSHSUPPLIER_HRL).
-define(COSNOTIFYCOMM_PUSHSUPPLIER_HRL, true).




-endif.


