%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_MappingFilter
%% Source: /home/vagrant/build-dir_14-10-22_14-39-46/otp-support/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_MAPPINGFILTER_HRL).
-define(COSNOTIFYFILTER_MAPPINGFILTER_HRL, true).




-endif.


