%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_ProxyConsumer
%% Source: /home/vagrant/build-dir_14-10-22_14-39-46/otp-support/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_PROXYCONSUMER_HRL).
-define(COSNOTIFYCHANNELADMIN_PROXYCONSUMER_HRL, true).




-endif.


