%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosPropertyService_PropertySetDef
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSPROPERTYSERVICE_PROPERTYSETDEF_HRL).
-define(COSPROPERTYSERVICE_PROPERTYSETDEF_HRL, true).




-endif.


