%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent
%% Source: /home/vagrant/build-dir_14-10-22_12-13-51/otp-support/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.3.6
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_HRL).
-define(COSTIMEREVENT_HRL, true).


-record('CosTimerEvent_TimerEventT', {utc, event_data}).


-endif.


